<div class="modal fade" id="changeEmailModal" tabindex="-1" aria-labelledby="changeEmailModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="changeEmailModalLabel">Изменение электронной почты</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div id="messages"></div>
        <form method='post' action='/profile/changeEmail' id='changeEmailForm'>
          <p>
            <label for="email" class='form-label'>Новая электронная почта</label>
          </p>
          <p>
            <?php
              echo $form->render('email',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <input type='submit' value='Отправить' class='btn btn-danger'/>
          </p>
        </form>
      </div>
      <p class='text-center'><button type="button" class="btn btn-success" data-dismiss="modal">Отмена</button></p>
    </div>
  </div>
</div>
<div class="modal fade" id="changeEmailConfirmationModal" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Подтвердите регистрацию</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>На Вашу электронную почту <b><span class='font-weight-bold' id='emailNotification'></span></b> было отправлено письмо с подтверждением. Для окончания регистрации перейдите по ссылке, указанной в письме.</p>
      </div>
      <div class="modal-footer">
        <p class='text-center'><button type="button" class="btn btn-success" data-dismiss="modal">OK</button></p>
      </div>
    </div>
  </div>
</div>
