<div class="modal fade" id="createCourseModal" tabindex="-1" aria-labelledby="changeCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="changeCourseModalLabel">Создание курса</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div id="createCourseMessages"></div>
        <form method='post' action='/profile/courses/create' id='createCourseForm'>
          <p>
            <label for="name" class='form-label'>Название курса</label>
          </p>
          <p>
            <?php
              echo $form->render('name',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <label for="nickname" class='form-label'>Ваше отображаемое имя</label>
          </p>
          <p>
            <?php
              echo $form->render('nickname',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <label for="password" class='form-label'>Пароль доступа</label>
          </p>
          <p>
            <?php
              echo $form->render('password',[
                'class' => 'form-control',
                'required' => 'required',
                'aria-describedby' => "passwordMin"
              ]);
            ?>
            <small class="form-text" id='passwordMin'>Минимум 8 символов</small>
          </p>
          <p>
            <label for="confirmPassword" class='form-label'>Подтверждение пароля доступа</label>
          </p>
          <p>
            <?php
              echo $form->render('confirmPassword',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <input type='submit' value='Создать' class='btn btn-success'/>
          </p>
        </form>
        <p class='text-center'><button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button></p>
      </div>
    </div>
  </div>
</div>
