<div class="modal fade" id="removeModal" tabindex="-1" aria-labelledby="removeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id='removeModalLabel'>Удаление учётной записи</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-danger text-center">
        <p>
          Обратите внимание, что полностью удалятся курсы, в которых Вы являетесь владельцем! Если Вы хотите их сохранить,
          назначьте другого владельца в настройках курса!
        </p>
        <p>Удаление необратимо, восстановить данные будет невозможно!</p>
        <p>Действительно удалить учётную запись?</p>
      </div>
      <div class="modal-footer">
        <button id='removeConfirmationBtn' type="button" class="btn btn-danger">Да</button>
        <button type="button" class="btn btn-success" data-dismiss="modal">Нет</button>
      </div>
    </div>
  </div>
</div>
