<div class="container  mt-3">
  <div class="row">
    <div class="col-lg">
      <h1 class='text-center font-weight-bold text-light'><?php echo $material -> title ?></h1>
       <div class='container-fluid text-light rounded bg-secondary mb-3 p-3'>
         <?php
            $material_id = $material -> id;
            $course_id = $course -> id;
            echo $material -> description;
            if(count($materialFiles) > 0) {
              echo "<div class='border text-center p-3'>";
              foreach($materialFiles as $materialFile) {
                $file_id = $materialFile -> id;
                $name = explode("__-__", $materialFile -> location);
                echo "<p><a class='text-light' href='/profile/course/$course_id/material/$material_id/file/$file_id'>$name[1]</a></p>";
              }
              echo "</div>";
            }
          ?>
       </div>
       <p class='text-center'><a class='text-warning' href='/profile/course/<?php echo $this -> view -> course -> id ?>'>Назад</a></p>
    </div>
  </div>
</div>
