<footer class="container-fluid text-center mt-3 text-light bg-primary">
  <div class="row align-items-center">
    <div class="col-lg">
      <p>Developed by <i><b>Viacheslav Davydov</b></i></p>
      <small><p>Donate BTC: <i><b>bc1qunmp09wgayj6ty0vwj3dhg7fzveu3y72sj3mkl</b></i></p></small>
    </div>
    <div class="col-lg">
      <!-- <p ><a href='/support' class='text-light'>Поддержка</a></p> -->
      <p>checkingboard@bk.ru</p>
    </div>
    <div class="col-lg">
      <p>Пользовательское соглашение</p>
    </div>
  </div>
</footer>
