<div id='mainImage'>
  <div class="container" >
    <div class="row align-items-center" >
      <div class="col-lg text-center">
        <h1 id='mainHeading' class='text-center text-success font-italic font-weight-bold mt-5'>СКАЖИ <span class='text-danger'>"ДА"</span> ОБРАЗОВАНИЮ</h1>
        <p><button id='mainButton' onclick="window.location.href = '/profile/courses'" type="button" class='btn btn-primary font-italic mt-5'>Начать развиваться</button></p>
        <p><button onclick="window.location.href = '/support'" type="button" class='btn btn-warning mt-5'>Поддержка</button></p>
      </div>
    </div>
  </div>
</div>
