<div id='materialsFileErrors'></div>
<form class='text-light' method='post' action='/profile/course/addMaterial' id='addMaterialForm'>
  <p>
    <label for="materialTitle" class='form-label'>Название</label>
  </p>
  <p>
    <?php
      echo $form->render('materialTitle',[
        'class' => 'form-control',
        'required' => 'required',
      ]);
    ?>
  </p>
  <p>
    <label for="materialDescription" class='form-label'>Описание</label>
  </p>
  <p style='color: black'>
    <?php
      echo $form->render('materialDescription',[
        'class' => 'form-control',
      ]);
    ?>
  </p>
  <p>
    <label for="materialFiles" class='form-label'>Файлы</label>
  </p>
  <div>
    <?php
      echo $form->render('materialFiles[]',[
        'multiple' => '',
        'id' => 'materialFiles',
        'data-max-size' => '8192'
      ]);
    ?>
    <a href='#' class='text-danger' id='clearMaterialsFiles'>Очистить</a>
    <p><small>Максимальный размер каждого файла - 8 Мб</small></p>
  </div>
  <p>
    <input id='addMaterialBtn' type='submit' value='Отправить' class='btn btn-success'/>
  </p>
  <input id='materialsFormCSRF' hidden name="materialsFormCSRF" value="">
  <input id='materialsFormCourseCode' name='courseId' hidden value="">
</form>
<?php
  echo $this -> view -> getPartial('partials/course/removeMaterialModal');
 ?>
<script>
  ClassicEditor
    .create( document.querySelector( '#materialDescription' ), {
      toolbar: {
        items: [
          'heading',
          '|',
          'bold',
          'italic',
          'alignment',
          'bulletedList',
          'numberedList',
          '|',
          'undo',
          'redo'
        ]
      },
    } )
    .then( editor => {
      window.editor = editor;
    } )
    .catch( error => {
      console.error( error );
    } );
</script>
