<div id='tasksFileErrors'></div>
<form class='text-light' method='post' action='/profile/course/addTask' id='addTaskForm'>
  <p>
    <label for="taskTitle" class='form-label'>Название</label>
  </p>
  <p>
    <?php
      echo $form->render('taskTitle',[
        'class' => 'form-control',
        'required' => 'required',
      ]);
    ?>
  </p>
  <p>
    <label for="taskTitle" class='form-label'>Максимальный балл</label>
  </p>
  <p>
    <?php
      echo $form->render('taskScore',[
        'class' => 'form-control',
        'required' => 'required',
        'min' => '1',
        'value' => '1'
      ]);
    ?>
  </p>
  <p>
    <label for="taskDescription" class='form-label'>Описание</label>
  </p>
  <p style='color: black'>
    <?php
      echo $form->render('taskDescription',[
        'class' => 'form-control',
      ]);
    ?>
  </p>
  <p>
    <label for="taskFiles" class='form-label'>Файлы</label>
  </p>
  <div>
    <?php
      echo $form->render('taskFiles[]',[
        'multiple' => '',
        'id' => 'taskFiles',
        'data-max-size' => '8192',
      ]);
    ?>
    <a href='#' class='text-danger' id='clearTasksFiles'>Очистить</a>
    <p><small>Максимальный размер каждого файла - 8 Мб</small></p>
  </div>
  <p>
    <input id='addTaskBtn' type='submit' value='Отправить' class='btn btn-success'/>
  </p>
  <input id='tasksFormCSRF' hidden name="tasksFormCSRF" value="">
  <input id='tasksFormCourseCode' name='courseId' hidden value="">
</form>
<?php
  echo $this -> view -> getPartial('partials/course/removeTaskModal');
 ?>
<script>
  ClassicEditor
    .create( document.querySelector( '#taskDescription' ), {
      toolbar: {
        items: [
          'heading',
          '|',
          'bold',
          'italic',
          'alignment',
          'bulletedList',
          'numberedList',
          '|',
          'undo',
          'redo'
        ]
      },
    } )
    .then( editorAddTask => {
      window.editorAddTask = editorAddTask;
    } )
    .catch( error => {
      console.error( error );
    } );
</script>
