<div class="modal fade" id="changeCoursePasswordModal" tabindex="-1" aria-labelledby="changeCoursePasswordModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="changeCoursePasswordModalLabel">Изменение пароля</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div id="changeCoursePasswordMessages"></div>
        <form method='post' action='/profile/course/changePassword' id='changeCoursePasswordForm'>
          <!-- <p>
            <label for="oldPassword" class='form-label'>Старый пароль</label>
          </p>
          <p> -->
            <?php
              // echo $form->render('oldPassword',[
              //   'class' => 'form-control',
              //   'required' => 'required'
              // ]);
            ?>
          <!-- </p> -->
          <p>
            <label for="newPassword" class='form-label'>Новый пароль</label>
          </p>
          <p>
            <?php
              echo $form->render('newPassword',[
                'class' => 'form-control',
                'required' => 'required',
                'aria-describedby' => "passwordMin"
              ]);
            ?>
            <small class="form-text" id='passwordMin'>Минимум 8 символов</small>
          </p>
          <p>
            <label for="confirmPassword" class='form-label'>Подтверждение пароля</label>
          </p>
          <p>
            <?php
              echo $form->render('confirmPassword',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <input type='submit' value='Отправить' class='btn btn-danger'/>
          </p>
        </form>
        <p class='text-center'><button type="button" class="btn btn-success" data-dismiss="modal">Отмена</button></p>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="changePasswordSuccessModal" tabindex="-1" aria-labelledby="changePasswordSuccessModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="changePasswordSuccessModalLabel">Изменение пароля</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Пароль успешно изменён!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-bs-dismiss="modal">ОК</button>
      </div>
    </div>
  </div>
</div>
