<div class="modal fade" id="changeCourseNameModal" tabindex="-1" aria-labelledby="changeCourseNameModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="changeCourseNameModalLabel">Изменение названия курса</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div id="changeCourseNameMessages"></div>
        <form method='post' action='/profile/course/changeName' id='changeCourseNameForm'>
          <p>
            <label for="newCourseName" class='form-label'>Новое название</label>
          </p>
          <p>
            <?php
              echo $form->render('newCourseName',[
                'class' => 'form-control',
                'required' => 'required'
              ]);
            ?>
          </p>
          <p>
            <input type='submit' value='Отправить' class='btn btn-success'/>
          </p>
        </form>
        <p class='text-center'><button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button></p>
      </div>
    </div>
  </div>
</div>
