<div id="materialsTabMessages"></div>
<?php
  if($role -> role != 'user') {
    echo $this -> view -> getPartial('partials/course/addMaterialsForm');
    echo $this -> view -> getPartial('partials/course/editMaterialModal');
  }

 ?>
<div class="table-responsive-lg">
  <table class="table table-striped table-dark table-hover" id='materialsTable'>
      <thead>
        <tr>
          <th>Название</th>
          <th>Дата & время публикации</th>
          <?php if($role -> role != 'user') echo "<th>Действия</th>" ?>
        </tr>
      </thead>
    <tbody>
   </tbody>
  </table>
</div>
