<div id="membersTabMessages"></div>
<p class='text-danger'>Если Вы заметили нежелательных участников, то удалите их, а затем обязательно поменяйте пароль курса!</p>
<div class="table-responsive-lg">
  <table class="table table-striped table-dark table-hover" id='membersTable'>
      <thead>
        <tr>
          <th>Имя</th>
          <th>Почта</th>
          <th>Роль</th>
          <th>Удаление</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
  </table>
</div>

<?php echo $this -> view -> getPartial('partials/course/removeMemberModal') ?>
<?php echo $this -> view -> getPartial('partials/course/changeMemberRoleModal') ?>
