<div class="modal fade" id="removeCourseModal" tabindex="-1" aria-labelledby="removeCourseModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id='removeCourseModalLabel'>Удаление курса</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-danger text-center">
        <p>Удаление необратимо, восстановить материалы курса, а также его участников будет невозможно!</p>
        <p>Действительно удалить курс?</p>
      </div>
      <div class="modal-footer">
        <button id='removeCourseConfirmationBtn' type="button" class="btn btn-danger">Да</button>
        <button type="button" class="btn btn-success" data-dismiss="modal">Нет</button>
      </div>
    </div>
  </div>
</div>
