<?php
  use Phalcon\Forms\Form;
  use Phalcon\Forms\Element\Password;
  $form = new Form();
  $form->add(
    new Password('password')
  );
  $form->add(
    new Password('confirmPassword')
  );
 ?>
<div class="container text-light text-center mt-3">
  <div class="row">
    <div class="col-lg">
      <h1 class='font-weight-bold'>Новый пароль</h1>
      <div id="messages"></div>
      <form method='post' action='/login/newPassword' id='newPasswordForm'>
        <p>
          <label for="password" class='form-label' >Пароль</label>
        </p>
        <p>
          <?php
            echo $form->render('password',[
                'class' => 'form-control',
                'required' => 'required',
                'aria-describedby' => "passwordMin"
            ]);
          ?>
          <small id='passwordMin' class="form-text">Минимум 8 символов</small>
        </p>
        <p>
          <label for="confirmPassword" class='form-label'>Подтверждение пароля</label>
        </p>
        <p>
          <?php
            echo $form->render('confirmPassword',[
                'class' => 'form-control',
                'required' => 'required'
            ]);
          ?>
        </p>
        <p>
          <input type='submit' value='Подтвердить' class='btn btn-primary'/>
        </p>
      </form>
      <p><a class='text-warning' href='/login'>Отмена</a></p>
    </div>
  </div>
</div>
